### ISSUE TITLE
ImportError: cannot import name 'container_abcs'

### ISSUE THREAD

**Issue by mk123qwe** [bzantium/pytorch-admm-prunning#1]
ImportError: cannot import name 'container_abcs'

**Comment by bzantium** [comment]
which version of pytorch are you using? It works on pytorch-1.3.0.

**Comment by mk123qwe** [comment]
> which version of pytorch are you using? It works on pytorch-1.3.0.

0.4.1.post2 cause this issue
1.0.0 cause another issue
Apply Pruning based on percentile
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main()
  File "main.py", line 165, in main
    mask = apply_l1_prune(model, device, args) if args.l1 else apply_prune(model, device, args)
  File "/home/pytorch-admm-pruning/utils.py", line 111, in apply_prune
    mask = prune_weight(param, device, args.percent[idx])
  File "/home/pytorch-admm-pruning/utils.py", line 92, in prune_weight
    mask = torch.Tensor(abs(weight_numpy) >= pcen).to(device)
TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.
9920512it [12:28, 13249.31it/s]

**Comment by mk123qwe** [comment]
pytorch1.3/ cuda10.1/ python3.69,code works properly.
